In [62]:
import requests

url = "https://api.coinpaprika.com/v1/tickers?quotes=USD"

response = requests.get(url)

response

In [63]:
response_json = response.json()

In [64]:
coin_list = response_json[:5]

In [65]:
coin_list

[{'id': 'btc-bitcoin',
  'name': 'Bitcoin',
  'symbol': 'BTC',
  'rank': 1,
  'total_supply': 20050291,
  'max_supply': 21000000,
  'beta_value': 0.969682,
  'first_data_at': '2010-07-17T00:00:00Z',
  'last_updated': '2026-06-30T17:15:16Z',
  'quotes': {'USD': {'price': 58322.90569032994,
    'volume_24h': 28018902003.997353,
    'volume_24h_change_24h': -5.809999942779541,
    'market_cap': 1169391056087,
    'market_cap_change_24h': -3.4700000286102295,
    'percent_change_15m': -0.20999999344348907,
    'percent_change_30m': -0.019999999552965164,
    'percent_change_1h': 0.12999999523162842,
    'percent_change_6h': -1.3700000047683716,
    'percent_change_12h': -1.649999976158142,
    'percent_change_24h': -3.4700000286102295,
    'percent_change_7d': -6.389999866485596,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 126173.1777846797,
    'ath_date': '2025-10-06T19:00:40Z',
    'percent_from_price_ath': -53.7}}},
 {'id': 'eth-ethereum',
  'name': 'Ethereum',
  'symbol': 'ETH',
  'rank': 2,
  'total_supply': 120232214,
  'max_supply': 0,
  'beta_value': 1.44937,
  'first_data_at': '2015-08-07T00:00:00Z',
  'last_updated': '2026-06-30T17:15:16Z',
  'quotes': {'USD': {'price': 1568.5270173044314,
    'volume_24h': 7318342422.276299,
    'volume_24h_change_24h': -15.949999809265137,
    'market_cap': 188891930240,
    'market_cap_change_24h': -3.509999990463257,
    'percent_change_15m': -0.17000000178813934,
    'percent_change_30m': 0.05000000074505806,
    'percent_change_1h': 0.36000001430511475,
    'percent_change_6h': -0.5199999809265137,
    'percent_change_12h': -0.9700000286102295,
    'percent_change_24h': -3.509999990463257,
    'percent_change_7d': -5.309999942779541,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 4946.229669645212,
    'ath_date': '2025-08-24T19:24:38Z',
    'percent_from_price_ath': -68.24}}},
 {'id': 'usdt-tether',
  'name': 'Tether',
  'symbol': 'USDT',
  'rank': 3,
  'total_supply': 190457881824,
  'max_supply': 0,
  'beta_value': -0.00170927,
  'first_data_at': '2015-02-25T00:00:00Z',
  'last_updated': '2026-06-30T17:15:16Z',
  'quotes': {'USD': {'price': 0.9985966544837946,
    'volume_24h': 92790736617.91748,
    'volume_24h_change_24h': 109.04000091552734,
    'market_cap': 184731333901,
    'market_cap_change_24h': -0.7200000286102295,
    'percent_change_15m': 0.029999999329447746,
    'percent_change_30m': 0.019999999552965164,
    'percent_change_1h': 0.029999999329447746,
    'percent_change_6h': 0,
    'percent_change_12h': 0,
    'percent_change_24h': 0.009999999776482582,
    'percent_change_7d': -0.029999999329447746,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 1.21549,
    'ath_date': '2015-02-25T17:04:00Z',
    'percent_from_price_ath': -17.84}}},
 {'id': 'bnb-binance-coin',
  'name': 'BNB',
  'symbol': 'BNB',
  'rank': 4,
  'total_supply': 139184442,
  'max_supply': 200000000,
  'beta_value': 1.04917,
  'first_data_at': '2017-07-25T00:00:00Z',
  'last_updated': '2026-06-30T17:15:16Z',
  'quotes': {'USD': {'price': 545.9989955041905,
    'volume_24h': 588536906.0933611,
    'volume_24h_change_24h': -19.209999084472656,
    'market_cap': 75994565521,
    'market_cap_change_24h': -2.740000009536743,
    'percent_change_15m': -0.11999999731779099,
    'percent_change_30m': 0.05999999865889549,
    'percent_change_1h': 0.17000000178813934,
    'percent_change_6h': -0.25999999046325684,
    'percent_change_12h': -0.9900000095367432,
    'percent_change_24h': -2.740000009536743,
    'percent_change_7d': -4.769999980926514,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 1370.9838437844724,
    'ath_date': '2025-10-13T09:00:44Z',
    'percent_from_price_ath': -60.11}}},
 {'id': 'usdc-usd-coin',
  'name': 'USDC',
  'symbol': 'USDC',
  'rank': 5,
  'total_supply': 73604840553,
  'max_supply': 0,
  'beta_value': -0.00366109,
  'first_data_at': '2018-10-09T00:00:00Z',
  'last_updated': '2026-06-30T17:15:16Z',
  'quotes': {'USD': {'price': 0.9997508068409844,
    'volume_24h': 14807928730.7899,
    'volume_24h_change_24h': -20.610000610351562,
    'market_cap': 73476380167,
    'market_cap_change_24h': -0.38999998569488525,
    'percent_change_15m': 0.009999999776482582,
    'percent_change_30m': 0,
    'percent_change_1h': 0,
    'percent_change_6h': -0.009999999776482582,
    'percent_change_12h': -0.019999999552965164,
    'percent_change_24h': 0.009999999776482582,
    'percent_change_7d': -0.019999999552965164,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 1.90619801,
    'ath_date': '2018-10-11T06:35:00Z',
    'percent_from_price_ath': -47.56}}}]

In [66]:
type(coin_list)

list

In [67]:
!pip install pandas

Requirement already satisfied: pandas in ./container.venv/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in ./container.venv/lib/python3.12/site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./container.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./container.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [113]:
import pandas as pd

coinz_df = pd.DataFrame(coin_list)

coinz_df

,id,name,symbol,rank,total_supply,max_supply,beta_value,first_data_at,last_updated,quotes
0,btc-bitcoin,Bitcoin,BTC,1,20050291,21000000,0.969682,2010-07-17T00:00:00Z,2026-06-30T17:15:16Z,"{'USD': {'price': 58322.90569032994, 'volume_2..."
1,eth-ethereum,Ethereum,ETH,2,120232214,0,1.449370,2015-08-07T00:00:00Z,2026-06-30T17:15:16Z,"{'USD': {'price': 1568.5270173044314, 'volume_..."
2,usdt-tether,Tether,USDT,3,190457881824,0,-0.001709,2015-02-25T00:00:00Z,2026-06-30T17:15:16Z,"{'USD': {'price': 0.9985966544837946, 'volume_..."
3,bnb-binance-coin,BNB,BNB,4,139184442,200000000,1.049170,2017-07-25T00:00:00Z,2026-06-30T17:15:16Z,"{'USD': {'price': 545.9989955041905, 'volume_2..."
4,usdc-usd-coin,USDC,USDC,5,73604840553,0,-0.003661,2018-10-09T00:00:00Z,2026-06-30T17:15:16Z,"{'USD': {'price': 0.9997508068409844, 'volume_..."

In [114]:
coinz_df = coinz_df[[ 'name', 'symbol',  'total_supply', 'first_data_at', 'quotes' ]]

In [115]:
coinz_df = coinz_df.rename(columns={ 'name': 'coin_name', 'first_data_at': 'invention_date'})

In [116]:
coinz_df["usd_price"] = coinz_df["quotes"].apply(lambda q: q["USD"]["price"])

In [117]:
coinz_df = coinz_df.drop(columns=['quotes'])

In [118]:
coinz_df["invention_date"] = pd.to_datetime(coinz_df["invention_date"], errors="coerce")

In [119]:
coinz_df["invention_date"] = pd.to_datetime(coinz_df["invention_date"], errors="coerce")

In [120]:
coinz_df["usd_price"] = coinz_df["usd_price"].round(4)

In [121]:
coinz_df["total_supply"] = coinz_df["total_supply"].map("{:,.0f}".format)

In [123]:
coinz_df

  coin_name symbol     total_supply invention_date   usd_price
0   Bitcoin    BTC       20,050,291     2010-07-17  58322.9057
1  Ethereum    ETH      120,232,214     2015-08-07   1568.5270
2    Tether   USDT  190,457,881,824     2015-02-25      0.9986
3       BNB    BNB      139,184,442     2017-07-25    545.9990
4      USDC   USDC   73,604,840,553     2018-10-09      0.9998

In [131]:
import os

from sqlalchemy import create_engine, text


DATABASE_NAME = os.getenv('DATABASE_NAME')
DATABASE_USER = os.getenv('DATABASE_USER')
DATABASE_PORT = os.getenv('DATABASE_PORT')
DATABASE_PASSWORD = os.getenv('DATABASE_PASSWORD')
DATABASE_HOST = os.getenv('DATABASE_HOST')    

try:
    engine = create_engine(
        f'postgresql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}'
    )

    # Load DataFrame to PostgreSQL
    coinz_df.to_sql('coins', engine, if_exists='replace', index=False)
    print(f"✓ Successfully loaded {len(coinz_df)} rows to 'coins' table")

except Exception as e:
    print(f"✗ Error loading data: {e}")

✓ Successfully loaded 5 rows to 'coins' table

In [128]:
pip install dotenv

Collecting dotenv
  Using cached dotenv-0.9.9-py2.py3-none-any.whl.metadata (279 bytes)
Collecting python-dotenv (from dotenv)
  Using cached python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Using cached dotenv-0.9.9-py2.py3-none-any.whl (1.9 kB)
Using cached python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Installing collected packages: python-dotenv, dotenv
Successfully installed dotenv-0.9.9 python-dotenv-1.2.2
Note: you may need to restart the kernel to use updated packages.

In [137]:
import logging
import sys
import importlib
import load

load = importlib.reload(load)

from extract import extract_coins
from transform import transform_coins
from load import load_coins


logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')


def main():
    try:
        coin_list = extract_coins()
        coinz_df = transform_coins(coin_list)
        load_coins(coinz_df)
        print('ETL process completed successfully.')
    except Exception:
        logging.exception('ETL process failed')
        sys.exit(1)


if __name__ == "__main__":
    main()

✓ Successfully loaded 5 rows to 'coins' table
✓ Retrieved 5 rows from database
('Bitcoin', 'BTC', 20050338, '2010-07-17', 58656.3707)
('Ethereum', 'ETH', 120232214, '2015-08-07', 1576.9296)
('Tether', 'USDT', 190457881824, '2015-02-25', 0.9984)
ETL process completed successfully.